<?php

namespace Database\Seeders;

use App\Models\Unit;
use Illuminate\Database\Seeder;

class UnitSeeder extends Seeder
{
    public function run(): void
    {
        $units = [
            ['nama_unit' => 'Infrastruktur', 'zona' => 'Umum', 'status' => 'Aktif'],
            ['nama_unit' => 'A1', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A2', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A3', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A4', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A5', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A6', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A7', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A8', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A9', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A10', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A11', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A12', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A13', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A14', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A15', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A16', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A17', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A18', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A19', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A20', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A21', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A22', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A23', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A24', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A25', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A26', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A27', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A28', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'A29', 'zona' => 'A', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B1', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B2', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B3', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B4', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B5', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B6', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B7', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B8', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B9', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B10', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B11', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B12', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B13', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B14', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B15', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B16', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B17', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B18', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B19', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B20', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B21', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B22', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B23', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B24', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B25', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B26', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B27', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B28', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'B29', 'zona' => 'B', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C1', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C2', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C3', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C4', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C5', 'zona' => 'C', 'status' => 'Aktif'],
            ['nama_unit' => 'C6', 'zona' => 'C', 'status' => 'Aktif'],
            ['nama_unit' => 'C7', 'zona' => 'C', 'status' => 'Aktif'],
            ['nama_unit' => 'C8', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C9', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C10', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C11', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C12', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C13', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C14', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C15', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C16', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C17', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C18', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C19', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C20', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C21', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C22', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C23', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C24', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C25', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C26', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C27', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C28', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'C29', 'zona' => 'C', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D1', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D2', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D3', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D4', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D5', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D6', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D7', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D8', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D9', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D10', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D11', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D12', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D13', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D14', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D15', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D16', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D17', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D18', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D19', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D20', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D21', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D22', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D23', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D24', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D25', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D26', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D27', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D28', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'D29', 'zona' => 'D', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E1', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E2', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E3', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E4', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E5', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E6', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E7', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E8', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E9', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E10', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E11', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E12', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E13', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E14', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E15', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E16', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E17', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E18', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E19', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E20', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E21', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E22', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E23', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E24', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E25', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E26', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E27', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E28', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'E29', 'zona' => 'E', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F1', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F2', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F3', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F4', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F5', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F6', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F7', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F8', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F9', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F10', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F11', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F12', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F13', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F14', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F15', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F16', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F17', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F18', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F19', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F20', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F21', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F22', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F23', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F24', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F25', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F26', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F27', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F28', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'F29', 'zona' => 'F', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G1', 'zona' => 'G', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G2', 'zona' => 'G', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G3', 'zona' => 'G', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G4', 'zona' => 'G', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G5', 'zona' => 'G', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G6', 'zona' => 'G', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G7', 'zona' => 'G', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G8', 'zona' => 'G', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G9', 'zona' => 'G', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G10', 'zona' => 'G', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G11', 'zona' => 'G', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G12', 'zona' => 'G', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G13', 'zona' => 'G', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G14', 'zona' => 'G', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G15', 'zona' => 'G', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G16', 'zona' => 'G', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G17', 'zona' => 'G', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G18', 'zona' => 'G', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G19', 'zona' => 'G', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G20', 'zona' => 'G', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G21', 'zona' => 'G', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G22', 'zona' => 'G', 'status' => 'Non Aktif'],
            ['nama_unit' => 'G23', 'zona' => 'G', 'status' => 'Non Aktif'],
        ];

        foreach ($units as $unit) {
            Unit::updateOrCreate(
                ['nama_unit' => $unit['nama_unit']],
                $unit
            );
        }
    }
}